#!/bin/sh

dev_inode () {
    _l=$(stat $1 | grep Device: | grep Inode: | tr -s '\t' ' ')
    _d=$(echo $_l | cut -d ' ' -f 2)
    _i=$(echo $_l | cut -d ' ' -f 4)
    _d=${_d%/*}
    echo $_d:$_i
}

etc_id=$(dev_inode /etc)
conf_id=$(dev_inode /conf/runtime/etc)

if [ "$etc_id" = "$conf_id" ]; then
    echo "/etc -> /conf/runtime/etc bind-mount already in place"
    exit 0
fi

LOWER="lowerdir=/conf/hardware/etc:/conf/software/etc:/etc"
UPPER="upperdir=/conf/changes/etc"
WORKDIR="workdir=/conf/workdir/etc"
RUNTIME="/conf/runtime/etc"

mount -t overlay overlay -o $LOWER,$UPPER,$WORKDIR $RUNTIME && \
    mount --bind $RUNTIME /etc
