#!/bin/sh

# mount $CONFFS
mount_conffs () {
    cat /proc/mounts | grep -q " $CONFFS " || mount $CONFFS
}

# load our configuration if it exists
load_config () {
    CONFIG=$SW/etc/sysconfig/ethernet
    if [ ! -e $CONFIG ]; then
        exit 0
    else
        . $CONFIG
    fi
}

# load any necessary modules
probe_modules () {
    if [ -z "$MODULES" ]; then
        return 0
    fi
    
    for m in $MODULES; do
        /sbin/modprobe $m
    done
}

# sort (and name) ethernet interfaces by MAC address
sort_by_mac () {
    mkdir -p $HW/etc/systemd/network
    macs=$(ip link ls | grep -vi loopback | grep link/ether | \
               sed 's/^ *//g' | cut -d ' ' -f 2 | sort)
    devs=${INTERFACES//,/ }

    for m in $macs; do
        d=${devs%% *}
        devs=${devs#* }
        f=$HW/etc/systemd/network/00-$d.link
        echo "Generating $f..."
        > $f cat <<EOF
[Match]
MACAddress=$m
[Link]
NamePolicy=disabled
Name=$d
EOF
    done
}


###########################
# main script

if [ "$1" = "-n" -o "$1" = "--dry-run" ]; then
    xeq=echo
    shift
fi

CONFFS=${1:-/conf}
SW=$CONFFS/software
HW=$CONFFS/hardware

mount_conffs
load_config
probe_modules

case $SETUP_METHOD in
  sort-mac)
      sort_by_mac
      ;;
  *)
      echo "Unknown setup method $SETUP_METHOD"
      exit 1
      ;;
esac
