#!/bin/sh

file_inode () {
    _l=$(stat $1 | grep Device: | grep Inode: | tr -s '\t' ' ')
    _d=$(echo $_l | cut -d ' ' -f 2); _d=${_d%/*}
    _i=$(echo $_l | cut -d ' ' -f 4)
    echo $_d:$_i
}

cmp_dev_inode () {
   _inode_a=$(file_inode $1)
   _inode_b=$(file_inode $2)

   if [ "$_inode_a" = "$_inode_b" ]; then
       return 0
   else
       return 1
   fi
}

prepare_directories () {
    $xeq mkdir -p $(echo $LOWER | tr ':' ' ') $UPPER $WORK $PRISTINE $RUNTIME
}

prepare_overlay () {
    $xeq mount -t overlay overlay \
        -o lowerdir=$LOWER:$PRISTINE,upperdir=$UPPER,workdir=$WORK $RUNTIME
}

bind_etc () {
    $xeq mount --bind $RUNTIME /etc
}

#########################
# main script

if [ "$1" = "-n" -o "$1" = "--dry-run" ]; then
    xeq=echo
    shift
fi

PRISTINE="/.pristine-etc"
LOWER="$CONFFS_PATH/hardware/etc:$CONFFS_PATH/software/etc"
UPPER="$CONFFS_PATH/changes/etc"
RUNTIME="$CONFFS_PATH/runtime/etc"
WORK="$CONFFS_PATH/workdir/etc"

if cmp_dev_inode /etc $RUNTIME; then
    echo "$RUNTIME already bind-mounted to /etc..."
    exit 0
fi

prepare_directories && prepare_overlay && bind_etc
