#!/bin/sh

mount_conffs () {
    cat /proc/mounts | grep -q " $CONFFS " || mount $CONFFS
}

check_marker () {
    mount_conffs

    if [ ! -e $MARKER ]; then
        echo "Reconfig-marker ($MARKER) not in place, already up-to-date..."
        return 1
    else
        return 0
    fi
}

clear_marker () {
    rm -f $MARKER
}

run_config_hooks () {
    hook_dir=${0%/*}
    if [ "$hook_dir" = "$0" ]; then
        hook_dir=/usr/share/gen-config/hooks
    fi
    
    hooks=$(ls $hook_dir/[0-9]* | sort)
    for h in $hooks; do
        if [ ! -x $h ]; then
            continue
        fi

        echo "Running conf-hook $h..."
        if ! $xeq $h; then            
            echo "$h: FAILED"
            failed_hooks="$failed_hooks $h"
        else
            echo "$h: OK"
        fi
    done

    if [ -n "$failed_hooks" ]; then
        echo "The following conf-hooks failed:"
        echo "    $failed_hooks"
        echo "$failed_hooks" >> $MARKER.failed
        return 1
    else
        return 0
    fi
}

#########################
# main script

if [ "$1" = "-n" -o "$1" = "--dry-run" ]; then
    xeq=echo
    shift
fi

CONFFS=${1:-/conf}
MARKER="$CONFFS/.reconfigure"

if check_marker; then
    run_config_hooks && clear_marker
fi
