#!/bin/sh

export CONFFS_LABEL=${CONFFS_LABEL:-config}
export CONFFS_PATH=${CONFFS_PATH:-/conf}

if [ "$1" = "-n" -o "$1" = "--dry-run" ]; then
    xeq=echo
    DRY_RUN="-n"
    shift
fi

hook_dir=${0%/*}
if [ "$hook_dir" = "$0" ]; then
    hook_dir=/usr/share/gen-config/hooks
fi

hooks=$(ls $hook_dir/[0-9]* | sort)
for h in $hooks; do
    if [ ! -x $h ]; then
        continue
    fi

    echo "Running conf-hook $h..."
    if ! $xeq $h $DRY_RUN; then
        echo "$h: FAILED"
        failed_hook="$h"
        break
    else
        echo "$h: OK"
    fi
done

if [ -n "$failed_hook" ]; then
    echo "conf-hook $failed_hook failed."
    echo "$failed_hook" >> $CONFFS_PATH/.reconfigure.failed
    return 1
else
    rm -f $CONFFS_PATH/.reconfigure
    return 0
fi
